server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp1it04x4xhh9bqhego.mysql.rds.aliyuncs.com:3306/sse-edusystem
    username: root
    password: root123456*
    driver-class-name: com.mysql.cj.jdbc.Driver
