server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp1it04x4xhh9bqhego.mysql.rds.aliyuncs.com:3306/sse-edusystem
    username: root
    password: root123456*
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 3617429882@qq.com
    password: tqdnzwqpvxhochjj
    default-encoding: UTF-8
    protocol: smtp
    properties.mail.smtp.ssl.enable: true

  #以谁来发送邮件
  #  mail.fromMail.addr=xxx1@qq.com

#config:
#  jwt:
#    # 加密密钥
#    secret: abcdefg1234567
#    # token有效时长
#    expire: 3600
#    # header 名称
#    header: token